packages:
  - "plugins/*"
  - "packages/*"
catalogMode: prefer

minimumReleaseAge: 7200 # 5 days in minutes
minimumReleaseAgeExclude:
  - '@types/node'

catalog:
  'turbo': 2.10.7
  'typescript': 7.0.2
  'oxfmt': 0.61.0
  'oxlint': 1.76.0
  '@extism/js-pdk': 1.1.1
